// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250609102910_scriptDatabase")]
    partial class scriptDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "BRC",
                            Origin = "GRU",
                            Value = 10m
                        },
                        new
                        {
                            Id = 2,
                            Destination = "SCL",
                            Origin = "BRC",
                            Value = 5m
                        },
                        new
                        {
                            Id = 3,
                            Destination = "CDG",
                            Origin = "GRU",
                            Value = 75m
                        },
                        new
                        {
                            Id = 4,
                            Destination = "SCL",
                            Origin = "GRU",
                            Value = 20m
                        },
                        new
                        {
                            Id = 5,
                            Destination = "ORL",
                            Origin = "GRU",
                            Value = 56m
                        },
                        new
                        {
                            Id = 6,
                            Destination = "CDG",
                            Origin = "ORL",
                            Value = 5m
                        },
                        new
                        {
                            Id = 7,
                            Destination = "ORL",
                            Origin = "SCL",
                            Value = 20m
                        },
                        new
                        {
                            Id = 8,
                            Destination = "CDG",
                            Origin = "GRU",
                            Value = 40m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "master@gmail.com",
                            Password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
